version: '3'

services:
  pear:
    build:
      context: .
    image: secret-test-build
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ENDPOINT=${DB_ENDPOINT}
    volumes:
      - /home/hong/projects/user_backend_v2/log:/logs/*.log
    env_file:
      - saby.env
    container_name: saby_spring_backend