spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://${DB_URL}:3306/SABY
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 20

auth:
  jwt:
    secret: secret
    exp:
      access: 1000000
