spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_ENDPOINT}:3306/SABY?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 6
        size-parameter: 6
auth:
  jwt:
    secret: ${SABY_SECRET}
    exp:
      access: ${SABY_ACCESS_EXP}
server:
  port: 8006