spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/savy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none

auth:
  jwt:
    secret: secret
    exp:
      access: 1000000
